# Generated by Django 5.1.1 on 2024-09-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_cart', '0005_alter_order_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-added_at']},
        ),
    ]
