# Generated by Django 5.1.1 on 2024-09-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_cart', '0006_alter_wishlist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default='123', max_digits=10),
            preserve_default=False,
        ),
    ]
