# Generated by Django 5.1.1 on 2024-09-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationrequest',
            name='admin_comment',
            field=models.TextField(blank=True, default='123'),
            preserve_default=False,
        ),
    ]
