# Generated by Django 5.1.1 on 2024-09-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_cancellationrequest_admin_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationrequest',
            name='admin_comment',
            field=models.TextField(),
        ),
    ]
