# Generated by Django 5.1.1 on 2024-09-22 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellationrequest',
            name='reason',
        ),
    ]
