# Generated by Django 5.1.1 on 2024-09-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_remove_cancellationrequest_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationrequest',
            name='reason',
            field=models.TextField(default='qwe'),
            preserve_default=False,
        ),
    ]
