# Generated by Django 5.0.7 on 2024-08-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_color_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='primary_image',
            field=models.ImageField(blank=True, default='path/to/default-image.jpg', null=True, upload_to='products/'),
        ),
    ]
