# Generated by Django 5.0.7 on 2024-08-18 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_primary_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='primary_image',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='color',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='products.Color'),
            preserve_default=False,
        ),
    ]
