# Generated by Django 5.0.7 on 2024-09-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_category_cat_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(blank=True, default='123', upload_to='photos/categories'),
            preserve_default=False,
        ),
    ]
