# Generated by Django 5.0.7 on 2024-09-01 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productimage_options_alter_category_cat_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
    ]
