# Generated by Django 5.1.1 on 2024-09-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_offer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='category',
            name='category_offer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='product_offer',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage applied to the product', max_digits=5),
        ),
    ]
